---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_extended_0.70.0_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.70.0_Linux-64bit.deb

script:
  - hugo --theme LoveIt -e production

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master